### ISSUE TITLE
PROTOCOL_ERROR is occured when I use python3.5

### ISSUE THREAD

**Issue by NetWilliam** [CleverTap/go-apns-server#3]
I want to use this mock server to test the qps of my server, howerver I have met this problem, 
my python ssl context configure as follow:

``` python

    ctx = ssl.create_default_context()
    ctx.options |= (ssl.OP_NO_TLSv1 | ssl.OP_NO_TLSv1_1 | ssl.OP_NO_COMPRESSION)
    ctx.set_ciphers('ECDHE+AESGCM')
    ctx.load_cert_chain(APNS_CERT)
    ctx.check_hostname = False
    ctx.verify_mode = ssl.CERT_NONE
    ctx.set_alpn_protocols(['h2'])
```

here is debug log:

2016/06/23 16:12:11 http2: server connection from 127.0.0.1:51079 on 0xc820016100
2016/06/23 16:12:11 http2: Framer 0xc82034a210: wrote SETTINGS len=18, settings: MAX_FRAME_SIZE=1048576, MAX_CONCURRENT_STREAMS=250, MAX_HEADER_LIST_SIZE=1048896
2016/06/23 16:12:11 http2: server: client 127.0.0.1:51079 said hello
2016/06/23 16:12:11 http2: Framer 0xc82034a210: read SETTINGS len=30, settings: HEADER_TABLE_SIZE=4096, ENABLE_PUSH=1, MAX_CONCURRENT_STREAMS=100, INITIAL_WINDOW_SIZE=65535, MAX_FRAME_SIZE=16384
2016/06/23 16:12:11 http2: server read frame SETTINGS len=30, settings: HEADER_TABLE_SIZE=4096, ENABLE_PUSH=1, MAX_CONCURRENT_STREAMS=100, INITIAL_WINDOW_SIZE=65535, MAX_FRAME_SIZE=16384
2016/06/23 16:12:11 http2: server processing setting [HEADER_TABLE_SIZE = 4096]
2016/06/23 16:12:11 http2: server processing setting [ENABLE_PUSH = 1]
2016/06/23 16:12:11 http2: server processing setting [MAX_CONCURRENT_STREAMS = 100]
2016/06/23 16:12:11 http2: server processing setting [INITIAL_WINDOW_SIZE = 65535]
2016/06/23 16:12:11 http2: server processing setting [MAX_FRAME_SIZE = 16384]
2016/06/23 16:12:11 http2: Framer 0xc82034a210: read SETTINGS flags=ACK len=0
2016/06/23 16:12:11 http2: server read frame SETTINGS flags=ACK len=0
2016/06/23 16:12:11 http2: Framer 0xc82034a210: read WINDOW_UPDATE len=4 (conn) incr=2147418112
2016/06/23 16:12:11 http2: server read frame WINDOW_UPDATE len=4 (conn) incr=2147418112
2016/06/23 16:12:11 http2: Framer 0xc82034a210: wrote SETTINGS flags=ACK len=0

2016/06/23 16:12:15 http2: Framer 0xc82034a210: read HEADERS flags=END_HEADERS stream=1 len=20
2016/06/23 16:12:15 http2: server read frame HEADERS flags=END_HEADERS stream=1 len=20
2016/06/23 16:12:15 http2: server decoded header field ":method" = "POST"
2016/06/23 16:12:15 http2: server decoded header field ":path" = "/"
2016/06/23 16:12:15 http2: server decoded header field "apns-topic" = "nonthingbig"
2016/06/23 16:12:15 http2: Framer 0xc82034a210: read DATA flags=END_STREAM stream=1 len=163 data="{\"r\": \"test-task-id\", \"l\": \"\", \"aps\": {\"badge\": 0, \"alert\": {\"body\": \"\u6709\u591a\u4e45\u6ca1\u4e0b\u53a8\u623f\u4e86\uff1f\", \"title\": null}, \"sound\": \"default\"}}"
2016/06/23 16:12:15 http2: server read frame DATA flags=END_STREAM stream=1 len=163 data="{\"r\": \"test-task-id\", \"l\": \"\", \"aps\": {\"badge\": 0, \"alert\": {\"body\": \"\u6709\u591a\u4e45\u6ca1\u4e0b\u53a8\u623f\u4e86\uff1f\", \"title\": null}, \"sound\": \"default\"}}"
2016/06/23 16:12:15 http2: Framer 0xc82034a210: wrote RST_STREAM stream=1 len=4 ErrCode=**PROTOCOL_ERROR**
2016/06/23 16:12:15 http2: Framer 0xc82034a210: wrote RST_STREAM stream=1 len=4 ErrCode=**STREAM_CLOSED**

**Comment by NetWilliam** [comment]
could anyone please tell me what the error mean? I have got no idea how to continue my work......

**Comment by judepereira** [comment]
Hey @NetWilliam, please direct this question to https://github.com/python-hyper/hyper-h2, as it looks more of a Hyper issue.
