### ISSUE TITLE
Get number of requests serviced

### ISSUE THREAD

**Issue by strongbull1** [CleverTap/go-apns-server#4]
Hi

First of all, thanks for amazing work

I was wondering if there is a way to show or get the number of requests serviced by a stub "till now" or a timerange ?

let me add some screenshots from CA DevTest (formerly Lisa) so it is bit easier to understand.
Looking for way to know

To know the count of total requests served
To further filter no of request served in last "X" time....lets say last 1 hour -> basically throughput
Links of screenshot
http://i.imgur.com/zBsMPU4.png
http://i.imgur.com/La3aKOT.png

**Comment by judepereira** [comment]
Hey @sukhdeepsinghkohli, this library was built for a quick and dirty smoke testing. I'm open to pull requests which would print the throughput per second, as well as the success/failure rate. However, integrating this with CA DevTest would be out of scope for this project.

**Comment by strongbull1** [comment]
Hi @judepereira 

Yep, if it can just show throughput or no of hits served in last "x" time...It will be great. 
DevTest was just example of what I was trying to say :)

Thanks

**Comment by strongbull1** [comment]
@judepereira  Did you get a chance to look in to this ?

**Comment by judepereira** [comment]
@sukhdeepsinghkohli No, I'm unable to add some benchmarking parameters to this project. However, I'd be glad if you could build it out.
